<CampaignMapScreen>:
    canvas.before:
        Color:
            rgba: 0.12, 0.18, 0.12, 1
        Rectangle:
            pos: self.pos
            size: self.size

<MapEnvironmentTile>:
    # กำหนดค่า Nearest Filter ให้ Texture ของ Tile ชัดเป๊ะ
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
    image_source: ''
    Image:
        source: root.image_source
        pos: root.pos
        size: root.size
        allow_stretch: True
        keep_ratio: False
        on_texture:
            self.texture.mag_filter = 'nearest' if self.texture else 'linear'
            self.texture.min_filter = 'nearest' if self.texture else 'linear'

<MapEnvironmentProp>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
    image_source: ''
    Image:
        source: root.image_source
        pos: root.pos
        size: root.size
        allow_stretch: True
        keep_ratio: True
        on_texture:
            self.texture.mag_filter = 'nearest' if self.texture else 'linear'
            self.texture.min_filter = 'nearest' if self.texture else 'linear'